/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 *
 * You can decode your strings by opening your VS Code terminal
 * and typing: npm run decode "<string>"
 *
 * Where you replace <string> with the string you (probably)
 * obtained from the ATT console.
 *
 * Make sure your string is wrapped in "double quotes".
 *
 * Here is an example string you can try.
 * Note the trailing comma at the end. This is intentional.
 *
 * 42230,264,42230,0,0,0,0,0,0,1065353216,1065353216,272188517,32,10962,0,0,2147510826,25836,0,0,0,0,0,0,532676608,532676608,136094258,2147483664,12047,935716111,2147483664,522610278,2147483648,0,1073751666,2147497679,0,0,0,0,0,0,266338304,266338304,68047129,1073741832,7793,2615341703,3221225480,261305139,1073741824,0,134218373,1879049508,3489660928,0,0,0,0,0,33292288,33292288,8505891,671088641,984,1879048192,0,0,|2,272188517,1,1871432223,1,
 */

import { decodeString } from 'att-string-transcoder';

const [string] = process.argv.slice(2);

if (typeof string === 'undefined' || string.length === 0) {
  throw new Error('You did not provide an ATT save string. Usage: npm run decode "<string>"');
}

const decodedString = decodeString(string);

console.log(JSON.stringify(decodedString, null, 2));
