/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */

import { Prefab } from 'att-string-transcoder';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */

function isPrefabInstance(creation: unknown): creation is Prefab {
  return creation instanceof Prefab;
}

/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */

const filePath = process.argv[2];

/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */

if (typeof filePath === 'undefined') {
  console.error(
    `You must specify the path of a creation file. For example:\nnpm run encode creations/example-damaged-longsword.ts`
  );
  process.exit(1);
}

/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */

const resolvedFilePath = fileURLToPath(new URL(join(dirname(import.meta.url), '..', filePath)));

/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */

if (!existsSync(resolvedFilePath)) {
  console.error(`Could not find creation file: ./${resolvedFilePath}`);
  process.exit(2);
}

/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */

const importKey = process.argv[3] ?? 'default';
const module = await import(resolvedFilePath);
const keys = Object.keys(module);

/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */

if (keys.length === 0) {
  console.error(
    `Creation file "${filePath}" has no exports. You must export a creation from this file to encode it.`
  );
  process.exit(3);
}

/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */

const { [importKey]: creation } = module;

/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */

if (typeof creation === 'undefined') {
  if (importKey === 'default') {
    console.error(`Creation file "./${filePath}" does not have a default export.`);
  } else {
    console.error(`Creation file "./${filePath}" does not have an export named "${importKey}".`);
  }

  console.log(`Did you mean one of these exports?${keys.map(key => `\n- ${key}`).join('')}`);
  process.exit(4);
}

/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */

if (!isPrefabInstance(creation)) {
  console.log(`"${importKey}" is not a Prefab. You must export a Prefab instance to encode.`);
  process.exit(5);
}

/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */

console.log(`\nEncoding "${importKey}" from "./${filePath}":\n`);
creation.print();

/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */
