/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */

import { start } from 'node:repl';
import * as transcoder from 'att-string-transcoder';

/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */

const repl = start();

/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */

for (const [key, value] of Object.entries(transcoder)) {
  Object.defineProperty(repl.context, key, {
    configurable: false,
    enumerable: true,
    value
  });
}

/**
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */
